package com.aprendiz.ragp.proyectopsp2.utilities;

public class Constants {

    public static final String DATABASE_NAME = "data.db";
    public static final int DATABASE_VALUE = 1;


    public static final String TableProject = "CREATE TABLE PROYECTO(IDPROYECTO INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT);";
    public static final String TableTimeLog = "CREATE TABLE TIMELOG (IDTIMELOG INTEGER PRIMARY KEY AUTOINCREMENT, PHASE TEXT, START TEXT, INTERRUPCION TEXT, STOP TEXT, DELTA TEXT, COMMENTS TEXT, PROYECTO INT, " +
            "FOREIGN KEY (PROYECTO) REFERENCES PROYECTO (IDPROYECTO));";
    public static final String TableDefectLog = "CREATE TABLE DEFECTLOG(IDDEFECTLOG INTEGER PRIMARY KEY AUTOINCREMENT, DATE TEXT, TYPE TEXT, FIXTIME TEXT, PHASEINJECTED TEXT, PHASEREMOVED TEXT, COMMENTS TEXT, PROYECTO INT," +
            "FOREIGN KEY (PROYECTO) REFERENCES PROYECTO (IDPROYECTO));";
    public static final String TableProjectPlanSummary= "CREATE TABLE PPS (IDPPS INTEGER PRIMARY KEY AUTOINCREMENT, PLANNING INT, DESIGN INT, CODE INT, COMPILE INT, UT INT, PM INT, PROYECTO INT, " +
            "FOREIGN KEY (PROYECTO) REFERENCES PROYECTO (IDPROYECTO));";


}
